version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  bofbof.cyrhades.com:
    image: anssi/fcsc2021-pwn-bofbof:latest
    ports:
      - "4000:4000"
